services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
#    env_file:
#      - ./server/.env
    # depends_on:
    #   - postgres
  
  #Just as example. Change whatever you need
  # postgres:
  #   image: postgres:16.4-alpine3.20
  #   ports:
  #     - 5432:5432
  #   env_file:
  #     - ./database/.env
  #   volumes:
  #     - ./database/postgres:/var/lib/postgresql/data
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-stage
    volumes:
      - ./coverage:/home/app/coverage
    # depends_on:
    #   - postgres
